#if os(Linux)
import Foundation
import XCTest
@testable import postmark

final class LinuxWatchCommandIntegrationTests: XCTestCase {
    
    private var testDirectoryURL: URL!
    private var contentDirectoryURL: URL!
    private var databaseFileURL: URL!
    
    override func setUpWithError() throws {
        testDirectoryURL = try makeTemporaryDirectory()
        contentDirectoryURL = testDirectoryURL.appendingPathComponent("content", isDirectory: true)
        databaseFileURL = testDirectoryURL.appendingPathComponent("postmark.sqlite")
        try FileManager.default.createDirectory(at: contentDirectoryURL, withIntermediateDirectories: true)
    }
    
    override func tearDownWithError() throws {
        DataStore.shared.close()
        try? FileManager.default.removeItem(at: testDirectoryURL)
        testDirectoryURL = nil
        contentDirectoryURL = nil
        databaseFileURL = nil
    }
    
    func testWatchCommandGeneratesContentAndDatabaseRowForMovedPostFolder() throws {
        let process = try startWatchCommand()
        defer {
            if process.isRunning {
                process.terminate()
            }
            process.waitUntilExit()
        }
        
        Thread.sleep(forTimeInterval: 0.5)
        
        let stagedPostDirectory = testDirectoryURL.appendingPathComponent("command-post", isDirectory: true)
        try FileManager.default.createDirectory(at: stagedPostDirectory, withIntermediateDirectories: true)
        try """
        # Command Post
        
        Generated by the Linux watch command.
        """.write(to: stagedPostDirectory.appendingPathComponent("command-post.md"), atomically: true, encoding: .utf8)
        
        let watchedPostDirectory = contentDirectoryURL.appendingPathComponent("command-post", isDirectory: true)
        try FileManager.default.moveItem(at: stagedPostDirectory, to: watchedPostDirectory)
        
        let generatedFileURL = watchedPostDirectory.appendingPathComponent("index.html")
        XCTAssertTrue(waitForCondition(timeout: 5) {
            FileManager.default.fileExists(atPath: generatedFileURL.path)
        }, "Timed out waiting for watch command to generate \(generatedFileURL.path)")
        XCTAssertEqual(try String(contentsOf: generatedFileURL), "<p>Generated by the Linux watch command.</p>")
        
        process.terminate()
        process.waitUntilExit()
        
        try DataStore.shared.open(databaseFile: databaseFileURL)
        let storedPost = try XCTUnwrap(DataStore.shared.getPost(with: "command-post"))
        XCTAssertEqual(storedPost.title, "Command Post")
        XCTAssertEqual(storedPost.hasGeneratedContent, true)
    }
    
    func testWatchCommandRegeneratesAfterAtomicSourceReplacement() throws {
        let process = try startWatchCommand()
        defer {
            if process.isRunning {
                process.terminate()
            }
            process.waitUntilExit()
        }
        
        let postDirectory = contentDirectoryURL.appendingPathComponent("atomic-post", isDirectory: true)
        try FileManager.default.createDirectory(at: postDirectory, withIntermediateDirectories: true)
        Thread.sleep(forTimeInterval: 0.2)
        let markdownFile = postDirectory.appendingPathComponent("atomic-post.md")
        try """
        # Atomic Post
        
        Original body.
        """.write(to: markdownFile, atomically: true, encoding: .utf8)
        
        let generatedFileURL = postDirectory.appendingPathComponent("index.html")
        XCTAssertTrue(waitForCondition(timeout: 5) {
            FileManager.default.fileExists(atPath: generatedFileURL.path)
        }, "Timed out waiting for initial generation")
        XCTAssertEqual(try String(contentsOf: generatedFileURL), "<p>Original body.</p>")
        
        let replacementFileURL = postDirectory.appendingPathComponent(".atomic-post.md.tmp")
        try """
        # Atomic Post
        
        Replaced body.
        """.write(to: replacementFileURL, atomically: true, encoding: .utf8)
        try FileManager.default.removeItem(at: markdownFile)
        try FileManager.default.moveItem(at: replacementFileURL, to: markdownFile)
        
        XCTAssertTrue(waitForCondition(timeout: 5) {
            (try? String(contentsOf: generatedFileURL)) == "<p>Replaced body.</p>"
        }, "Timed out waiting for regenerated content")
    }
    
    private func startWatchCommand() throws -> Process {
        let executableURL = try postmarkExecutableURL()
        let process = Process()
        let outputPipe = Pipe()
        process.executableURL = executableURL
        process.arguments = [
            "watch",
            contentDirectoryURL.path,
            "-db",
            databaseFileURL.path,
            "-f",
            "-l",
            "debug"
        ]
        process.standardOutput = outputPipe
        process.standardError = outputPipe
        
        try process.run()
        Thread.sleep(forTimeInterval: 0.5)
        
        return process
    }
    
    private func postmarkExecutableURL() throws -> URL {
        let bundleURL = Bundle.main.bundleURL
        let candidateURLs = [
            bundleURL.appendingPathComponent("postmark"),
            bundleURL.deletingLastPathComponent().appendingPathComponent("postmark"),
            bundleURL.deletingLastPathComponent().appendingPathComponent("debug/postmark")
        ]
        
        guard let executableURL = candidateURLs.first(where: { FileManager.default.isExecutableFile(atPath: $0.path) }) else {
            throw XCTSkip("Could not find built postmark executable. Checked: \(candidateURLs.map(\.path).joined(separator: ", "))")
        }
        
        return executableURL
    }
}
#endif
